ScholarshipSolution/Models/University.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ScholarshipSolution.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.Web;

    public partial class University
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public University()
        {
            this.Professors = new HashSet<Professor>();
            this.Scholarships = new HashSet<Scholarship>();
        }
    
        public int UniID { get; set; }
        public string UniName { get; set; }
        public Nullable<double> UniRating { get; set; }
        [DisplayName("Upload File")]
        public string UniPicture { get; set; }
        public HttpPostedFileBase ImageFile { get; set; }
        public string City { get; set; }
        public string Country { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Professor> Professors { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Scholarship> Scholarships { get; set; }
    }
}

ScholarshipSolution/Controllers/UniversitiesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using ScholarshipSolution.Models;

namespace ScholarshipSolution.Controllers
{
    public class UniversitiesController : Controller
    {
        private final_32_dbbEntities db = new final_32_dbbEntities();

        // GET: Universities
        public ActionResult Index()
        {
            return View(db.Universities.ToList());
        }

        public ActionResult ShowAll()
        {
            return View(db.Universities.ToList());
        }

        public ActionResult SearchUni(string searching)
        {
            return View(db.Universities.Where(x => x.UniName.Contains(searching) || x.City.Contains(searching) || x.Country.Contains(searching) || searching == null).ToList()); 
        }

        // GET: Universities/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            University university = db.Universities.Find(id);
            if (university == null)
            {
                return HttpNotFound();
            }
            return View(university);
        }

        // GET: Universities/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Universities/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "UniID,UniName,UniRating,UniPicture,City,Country")] University university, University imageModel)
        {
            string fileName = Path.GetFileNameWithoutExtension(imageModel.ImageFile.FileName);
            string extension = Path.GetExtension(imageModel.ImageFile.FileName);
            fileName = fileName + DateTime.Now.ToString("yymmssfff") + extension;
            imageModel.UniPicture = "~/Content/UniversityPicture/" + fileName;
            fileName = Path.Combine(Server.MapPath("~/Content/UniversityPicture/"), fileName);
            imageModel.ImageFile.SaveAs(fileName);
            if (ModelState.IsValid)
            {
                //db.Universities.Add(university);
                db.Universities.Add(imageModel);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(university);
        }

        // GET: Universities/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            University university = db.Universities.Find(id);
            if (university == null)
            {
                return HttpNotFound();
            }
            return View(university);
        }

        // POST: Universities/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "UniID,UniName,UniRating,UniPicture,City,Country")] University university, University imageModel)
        {
            string fileName = Path.GetFileNameWithoutExtension(imageModel.ImageFile.FileName);
            string extension = Path.GetExtension(imageModel.ImageFile.FileName);
            fileName = fileName + DateTime.Now.ToString("yymmssfff") + extension;
            imageModel.UniPicture = "~/Content/UniversityPicture/" + fileName;
            fileName = Path.Combine(Server.MapPath("~/Content/UniversityPicture/"), fileName);
            imageModel.ImageFile.SaveAs(fileName);
            if (ModelState.IsValid)
            {
                db.Entry(university).State = EntityState.Modified;
                db.Entry(imageModel).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(university);
        }

        // GET: Universities/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            University university = db.Universities.Find(id);
            if (university == null)
            {
                return HttpNotFound();
            }
            return View(university);
        }

        // POST: Universities/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            University university = db.Universities.Find(id);
            db.Universities.Remove(university);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

ScholarshipSolution/Views/Universities/Create.cshtml
@model ScholarshipSolution.Models.University

@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_LayoutAdmin.cshtml";
}

<div class="main-container">
    <div class="pd-ltr-20 xs-pd-20-10">

        @using (Html.BeginForm("Create", "Universities", FormMethod.Post, new {enctype = "multipart/form-data" }))
        {
            @Html.AntiForgeryToken()

            <div class="form-horizontal">
                <h4>University</h4>
                <hr />
                @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                <div class="form-group">
                    @Html.LabelFor(model => model.UniName, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.UniName, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.UniName, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.UniRating, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.UniRating, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.UniRating, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.UniPicture, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        <input type="file" name="ImageFile" required>
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.City, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.City, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.City, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.Country, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.Country, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.Country, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    <div class="col-md-offset-2 col-md-10">
                        <input type="submit" value="Create" class="btn btn-default" />
                    </div>
                </div>
            </div>
        }

    </div>
</div>

        

ScholarshipSolution/Views/Universities/Delete.cshtml
@model ScholarshipSolution.Models.University

@{
    ViewBag.Title = "Delete";
    Layout = "~/Views/Shared/_LayoutAdmin.cshtml";
}

<div class="main-container">
    <div class="pd-ltr-20 xs-pd-20-10">
        <h3>Are you sure you want to delete this?</h3>
        <div>
            <h4>University</h4>
            <hr />
            <dl class="dl-horizontal">
                <dt>
                    @Html.DisplayNameFor(model => model.UniName)
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.UniName)
                </dd>

                <dt>
                    @Html.DisplayNameFor(model => model.UniRating)
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.UniRating)
                </dd>

                <dt>
                    @Html.DisplayNameFor(model => model.UniPicture)
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.UniPicture)
                </dd>

                <dt>
                    @Html.DisplayNameFor(model => model.City)
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.City)
                </dd>

                <dt>
                    @Html.DisplayNameFor(model => model.Country)
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.Country)
                </dd>

            </dl>

            @using (Html.BeginForm())
            {
                @Html.AntiForgeryToken()

                <div class="form-actions no-color">
                    <input type="submit" value="Delete" class="btn btn-default" /> |
                    @Html.ActionLink("Back to List", "Index")
                </div>
            }
        </div>
    </div>
</div>

        

ScholarshipSolution/Views/Universities/Details.cshtml
@model ScholarshipSolution.Models.University

@{
    ViewBag.Title = "Details";
    Layout = "~/Views/Shared/_LayoutAdmin.cshtml";
}

<div class="main-container">
    <div class="pd-ltr-20 xs-pd-20-10">
        <div class="min-height-200px">
            <div class="page-header">
                <div class="row">
                    <div class="col-md-6 col-sm-12">
                        <div class="title">
                            <h4>University Details</h4>
                        </div>
                    </div>
                </div>
            </div>
            <div class="card-box mb-30">
                <dl class="dl-horizontal">
                    <dt>
                        @Html.DisplayNameFor(model => model.UniName)
                    </dt>

                    <dd>
                        @Html.DisplayFor(model => model.UniName)
                    </dd>

                    <dt>
                        @Html.DisplayNameFor(model => model.UniRating)
                    </dt>

                    <dd>
                        @Html.DisplayFor(model => model.UniRating)
                    </dd>

                    <dt>
                        @Html.DisplayNameFor(model => model.UniPicture)
                    </dt>

                    <dd>
                        <img src="@Url.Content(Model.UniPicture)" width="250" height="250" />
                    </dd>

                    <dt>
                        @Html.DisplayNameFor(model => model.City)
                    </dt>

                    <dd>
                        @Html.DisplayFor(model => model.City)
                    </dd>

                    <dt>
                        @Html.DisplayNameFor(model => model.Country)
                    </dt>

                    <dd>
                        @Html.DisplayFor(model => model.Country)
                    </dd>

                </dl>
            </div>
            <p>
                @Html.ActionLink("Edit", "Edit", new { id = Model.UniID })
            </p>
        </div>
    </div>
</div>

            

ScholarshipSolution/Views/Universities/Edit.cshtml
@model ScholarshipSolution.Models.University

@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/_LayoutAdmin.cshtml";
}

<div class="main-container">
    <div class="pd-ltr-20 xs-pd-20-10">
        <div class="min-height-200px">
            <div class="page-header">
                <div class="row">
                    <div class="col-md-6 col-sm-12">
                        <div class="title">
                            <h4>University Edit</h4>
                        </div>
                    </div>
                </div>
            </div>
            <div class="card-box mb-30">
                @using (Html.BeginForm())
                {
                    @Html.AntiForgeryToken()

                    <div class="form-horizontal">
                        <h4>University</h4>
                        <hr />
                        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                        @Html.HiddenFor(model => model.UniID)

                        <div class="form-group">
                            @Html.LabelFor(model => model.UniName, htmlAttributes: new { @class = "control-label col-md-2" })
                            <div class="col-md-10">
                                @Html.EditorFor(model => model.UniName, new { htmlAttributes = new { @class = "form-control" } })
                                @Html.ValidationMessageFor(model => model.UniName, "", new { @class = "text-danger" })
                            </div>
                        </div>

                        <div class="form-group">
                            @Html.LabelFor(model => model.UniRating, htmlAttributes: new { @class = "control-label col-md-2" })
                            <div class="col-md-10">
                                @Html.EditorFor(model => model.UniRating, new { htmlAttributes = new { @class = "form-control" } })
                                @Html.ValidationMessageFor(model => model.UniRating, "", new { @class = "text-danger" })
                            </div>
                        </div>

                        <div class="form-group">
                            @Html.LabelFor(model => model.UniPicture, htmlAttributes: new { @class = "control-label col-md-2" })
                            <div class="col-md-10">
                                @Html.EditorFor(model => model.UniPicture, new { htmlAttributes = new { @class = "form-control" } })
                                @Html.ValidationMessageFor(model => model.UniPicture, "", new { @class = "text-danger" })
                            </div>
                        </div>

                        <div class="form-group">
                            @Html.LabelFor(model => model.City, htmlAttributes: new { @class = "control-label col-md-2" })
                            <div class="col-md-10">
                                @Html.EditorFor(model => model.City, new { htmlAttributes = new { @class = "form-control" } })
                                @Html.ValidationMessageFor(model => model.City, "", new { @class = "text-danger" })
                            </div>
                        </div>

                        <div class="form-group">
                            @Html.LabelFor(model => model.Country, htmlAttributes: new { @class = "control-label col-md-2" })
                            <div class="col-md-10">
                                @Html.EditorFor(model => model.Country, new { htmlAttributes = new { @class = "form-control" } })
                                @Html.ValidationMessageFor(model => model.Country, "", new { @class = "text-danger" })
                            </div>
                        </div>

                        <div class="form-group">
                            <div class="col-md-offset-2 col-md-10">
                                <input type="submit" value="Save" class="btn btn-default" />
                            </div>
                        </div>
                    </div>
                }
            </div>
        </div>
    </div>
</div>

ScholarshipSolution/Views/Universities/Index.cshtml
@model IEnumerable<ScholarshipSolution.Models.University>

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_LayoutAdmin.cshtml";
}


<div class="main-container">
    <div class="pd-ltr-20 xs-pd-20-10" >
        <div class="min-height-200px">
            <div class="page-header">
                <div class="row">
                    <div class="col-md-6 col-sm-12">
                        <div class="title">
                            <h4>University Database</h4>
                        </div>
                    </div>
                    <div class="col-md-6 col-sm-12 text-right">
                        <div class="dropdown">
                            <a class="btn btn-primary dropdown-toggle" href="~/Universities/Create/" role="button">
                                Add New
                            </a>
                        </div>
                    </div>
                </div>
            </div>
            <!-- University Datatable start -->
            <div class="card-box mb-30">
                <div class="pd-20">
                    <h4 class="text-blue h4">Universities</h4>
                </div>
                <div>
                    <table class="table">
                        <tr>
                            <th>@Html.DisplayNameFor(model => model.UniName)</th>
                            <th>@Html.DisplayNameFor(model => model.UniRating)</th>
                            <th>@Html.DisplayNameFor(model => model.City)</th>
                            <th>@Html.DisplayNameFor(model => model.Country)</th>
                            <th>Action</th>
                        </tr>

                        @foreach (var item in Model)
                        {
                            <tr>
                                <td>@Html.DisplayFor(modelItem => item.UniName)</td>
                                <td>@Html.DisplayFor(modelItem => item.UniRating)</td>
                                <td>@Html.DisplayFor(modelItem => item.City)</td>
                                <td>@Html.DisplayFor(modelItem => item.Country)</td>
                                <td>
                                    @Html.ActionLink("Details", "Details", new { id = item.UniID })
                                    @Html.ActionLink("Edit", "Edit", new { id = item.UniID }) 
                                    @Html.ActionLink("Delete", "Delete", new { id = item.UniID })
                                </td>
                            </tr>
                        }

                        
                    </table>
                </div>
            </div>
            <!-- University Datatable End -->
        </div>
    </div>
</div>






















@*<p>
        @Html.ActionLink("Create New", "Create")
    </p>*@
@*<table class="table">
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.UniName)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.UniRating)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.UniPicture)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.City)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Country)
            </th>
            <th></th>
        </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.UniName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.UniRating)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.UniPicture)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.City)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Country)
            </td>
            <td>
                @Html.ActionLink("Edit", "Edit", new { id = item.UniID }) |
                @Html.ActionLink("Details", "Details", new { id = item.UniID }) |
                @Html.ActionLink("Delete", "Delete", new { id = item.UniID })
            </td>
        </tr>
    }

    </table>*@

ScholarshipSolution/Views/Universities/SearchUni.cshtml
@model IEnumerable<ScholarshipSolution.Models.University>

@{
    ViewBag.Title = "SearchUni";
    Layout = null;
}

<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta content="width=device-width, initial-scale=1.0" name="viewport">
    <title>Scholarship Solution</title>
    <!-- Site favicon -->
    <link rel="apple-touch-icon" sizes="180x180" href="~/Content/vendors_admin/images/logo.png">
    <link rel="icon" type="image/png" sizes="32x32" href="~/Content/vendors_admin/images/favicon-32x32.png">
    <link rel="icon" type="image/png" sizes="16x16" href="~/Content/vendors_admin/images/favicon-16x16.png">
    <link href="https://fonts.googleapis.com/css?family=Open+Sans:300,400,600,700" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Poppins:400,800" rel="stylesheet" />

    @Styles.Render("~/Content/vendor/bootstrap/css/bootstrap.min.css")
    @Styles.Render("~/Content/vendor/bootstrap-icons/bootstrap-icons.css")
    @Styles.Render("~/Content/cssassets/vendor/aos/aos.css")
    @Styles.Render("~/Content/vendor/remixicon/remixicon.css")
    @Styles.Render("~/Content/vendor/swiper/swiper-bundle.min.css")
    @Styles.Render("~/Content/vendor/glightbox/css/glightbox.min.css")
    @Styles.Render("~/Content/css/style.css")
    @Styles.Render("~/Content/css/profprofile.css")
    @Styles.Render("~/Content/css/main.css")
    @Scripts.Render("~/bundles/modernizr")
</head>

<body>
    <!-- ======= Header ======= -->
    <header id="header" class="header fixed-top">
        <div class="container-fluid container-xl d-flex align-items-center justify-content-between">

            <a href="#hero" class="logo d-flex align-items-center">
                <img src="~/Content/img/logo.png" alt="">
                <span style="color:#ff758f;">Scholarship Solution</span>
            </a>

            <nav id="navbar" class="navbar">
                <ul>
                    <li><a class="nav-link scrollto" href="#hero">Home</a></li>
                    <li><a class="nav-link scrollto" href="~/Universities/ShowAll">University</a></li>
                    <li><a class="nav-link scrollto" href="~/Students/Index">Students</a></li>
                    <li><a class="nav-link scrollto" href="~/Home/Index/#contact">Contact</a></li>
                    <li><a class="nav-link scrollto" href="~/Home/Index/#team">About Us</a></li>
                    <li><a class="nav-link scrollto " style="margin-left:35px; " href="~/Professors/Profile/">My Profile</a></li>
                    <li><a class="getstarted scrollto" href="~/Home/Index/">Logout</a></li>
                </ul>
                <i class="bi bi-list mobile-nav-toggle"></i>
            </nav><!-- .navbar -->
        </div>
    </header>

    <!-- Header -->
    <main>
        <section id="portfolio" class="portfolio">
            <div class="container" data-aos="fade-up">
                <header class="section-header">
                    <h2>Universities</h2>
                    <p>Check our latest work</p>
                </header>
                
                <div>
                    @using (Html.BeginForm("SearchUni", "Universities", FormMethod.Get))
                    {
                        //@Html.TextBox("searching")<input type="submit" value="Search" />
                        @Html.TextBox("searching", null, new { id = "choices-text-preset-values", @class = "form-control", @type = "text", @placeholder = "Type to search..." })<input type="submit" value="Search" />
                    }
                </div>
                <br ><br><br>
                <div class="row gy-4 portfolio-container" data-aos="fade-up" data-aos-delay="200">
                    @if (Model.Count() == 0)
                    {
                        <p style="color:red"> No Match Found!</p>
                    }
                    else
                    {
                        foreach (var item in Model)
                        {
                            <div class="col-lg-4 col-md-6 portfolio-item">
                                <div class="portfolio-wrap">
                                    <img src="@Url.Content(item.UniPicture)" class="img-fluid" width="350" height="350" alt="">
                                    <div class="portfolio-info">
                                        <h4>@Html.DisplayFor(modelItem => item.UniName)</h4>
                                        <p>@Html.DisplayFor(modelItem => item.City), @Html.DisplayFor(modelItem => item.Country)</p>
                                        <span>@Html.DisplayFor(modelItem => item.UniRating)</span>
                                        <div class="portfolio-links">
                                            <a href="@Url.Content(item.UniPicture)" data-gallery="portfolioGallery" class="portfokio-lightbox" title="App 1"><i class="bi bi-plus"></i></a>
                                            <a href="#" title="More Details"><i class="bi bi-link"></i></a>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        }
                    }
                </div>
            </div>
        </section>
    </main>


    <!-- Vendor JS Files -->
    @Scripts.Render("~/assets/vendor/bootstrap/js/bootstrap.bundle.js")
    @Scripts.Render("~/assets/vendor/aos/aos.js")
    @Scripts.Render("~/assets/vendor/php-email-form/validate.js")
    @Scripts.Render("~/assets/vendor/swiper/swiper-bundle.min.js")
    @Scripts.Render("~/assets/vendor/purecounter/purecounter.js")
    @Scripts.Render("~/assets/vendor/isotope-layout/isotope.pkgd.min.js")
    @Scripts.Render("~/assets/vendor/glightbox/js/glightbox.min.js")
    @Scripts.Render("~/Content/js/choices.js")

    <!-- Template Main JS File -->
    @Scripts.Render("~/assets/js/main.js")
    @*@RenderSection("scripts", required: false)*@
</body>
</html>